version: 2
aliases:
  - &docker_image circleci/python:3.6-stretch
  - &dependencies
    name: Make virtualenv and install dependencies
    command: |
      python3 -m venv ~/venv
      echo ". ~/venv/bin/activate" >> $BASH_ENV
      source $BASH_ENV
      pip install -q -U pip setuptools
      make dependencies
  - &test_boilerplate
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run:
          name: Install postgres
          command: |
            sudo apt-get update && \
              sudo apt-get install \
                postgresql-9.6
      - run:
          <<: *dependencies
      - run: make test
      - store_test_results:
           path: /tmp/test-reports
      - store_artifacts:
           path: /tmp/test-reports
jobs:
  temple_check:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run:
          <<: *dependencies
      - run: temple update --check
  lint:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run:
          name: Install pandoc
          command: |
            sudo apt-get update && \
              sudo apt-get install \
                pandoc
      - run:
          <<: *dependencies
      - run: make validate
  test_py35:
    docker:
      - image: circleci/python:3.5-stretch
    <<: *test_boilerplate
  test_py36:
    docker:
      - image: circleci/python:3.6-stretch
    <<: *test_boilerplate
  test_py37:
    docker:
      - image: circleci/python:3.7-stretch
    <<: *test_boilerplate
  deploy:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2a:d0:4c:ad:c8:3a:4f:47:19:e2:52:0d:26:a4:6d:10"
      - run:
          name: Install pandoc
          command: |
            sudo apt-get update && \
              sudo apt-get install \
                pandoc
      - run:
          <<: *dependencies
      - run: pip install -q -r deploy_requirements.txt
      - run: python3 deploy.py prod

workflows:
  version: 2
  checks_and_deploy:
    jobs:
      - temple_check
      - lint
      - test_py35
      - test_py36
      - test_py37
      - deploy:
          requires:
            - temple_check
            - lint
            - test_py35
            - test_py36
            - test_py37
          filters:
            branches:
              only:
                - master
